---
# A pre-commit hook for testing unreleased changes
# Run from tox with: tox -e py39-hook
repos:
  - repo: local
    hooks:
      - id: mdformat
        name: mdformat-from-tox
        entry: mdformat
        files: tests/pre-commit-test.md
        types: [markdown]
        language: system
      - id: mdformat-with-args
        name: mdformat-with-args
        entry: mdformat
        args: [--wrap=40, --number]
        files: tests/pre-commit-test-numbered.md
        types: [markdown]
        language: system
      - id: mdformat-with-semantic-arg
        name: mdformat-with-semantic-arg
        entry: mdformat
        args: [--align-semantic-breaks-in-lists]
        files: tests/pre-commit-test-align_semantic_breaks_in_lists.md
        types: [markdown]
        language: system
      - id: mdformat-with-ignore-missing-references
        name: mdformat-with-ignore-missing-references
        entry: mdformat
        args: [--ignore-missing-references]
        files: tests/pre-commit-test-ignore_missing_references.md
        types: [markdown]
        language: system
