---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

rules:
  empty-values: enable
  float-values: enable
  line-length: disable
  octal-values: enable
  # quoted-strings: enable
  comments:
    min-spaces-from-content: 1
