[tools]
"cargo:mdsf" = "latest"
"pipx:prek" = "latest"
"pipx:pytest-watcher" = "latest"
"pipx:tox" = {uvx_args = "--with tox-uv>=1.29.0", version = "latest"}
python = ["3.10.15", "3.14.0"]
uv = "latest"
